version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: filament-laravel
    container_name: filament_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./vendor:/var/www/vendor
    depends_on:
      - db
    networks:
      - filament_net

  db:
    image: mysql:8.0
    container_name: filament_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: filament_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - filament_net

  nginx:
    image: nginx:latest
    container_name: filament_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - filament_net

volumes:
  db_data:

networks:
  filament_net:
